---
title: "COPING_participation_analysis"
author: "Steven Bright"
date: "04/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Clean global environment}

remove(list = ls())

```

#Call libraries

```{r Install packages}

#install.packages("tidyverse")

```

```{r Load libraries}

library(tidyverse)

```

#Read in data

```{r Source paths}

source("..//COPING_participation_paths.r")

```

```{r Read in glad coping participation data}

glad_coping_participation_raw <- read_rds(paste0(processed_data_path, processed_data_name))

#Check data
glad_coping_participation_raw %>% 
  head()

```

#Create tables for chi2 tests
##Sociodemographics variables

Variables:

Age (continuous - Not applicable)
Gender
Ethnicity
Education
Employment
Partnership status

```{r Create contingency table for gender}

gender_contingency_table <- table(glad_coping_participation_raw$gender_recode_labelled,
                                  glad_coping_participation_raw$completed_baseline_labelled)

#Check output
gender_contingency_table

```

```{r Create contingency table for ethnicity}

ethnicity_contingency_table <- table(glad_coping_participation_raw$ethnicity_labelled,
                                     glad_coping_participation_raw$completed_baseline_labelled)

#Check output
ethnicity_contingency_table

```

```{r Create contingency table for Education}

education_contingency_table <- table(glad_coping_participation_raw$highest_education,
                                     glad_coping_participation_raw$completed_baseline_labelled)

#Check output
education_contingency_table

```

```{r Create contingency table for employment}

employment_contingency_table <- table(glad_coping_participation_raw$employment_labelled,
                                      glad_coping_participation_raw$completed_baseline_labelled)

#Check output
employment_contingency_table

```

```{r Partnership status}

partnership_contingency_table <- table(glad_coping_participation_raw$partnership_status_labelled,
                                       glad_coping_participation_raw$completed_baseline_labelled)

#Check output
partnership_contingency_table

```

