---
title: "Tables_and_plots"
author: "Steven Bright"
date: "22/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Clean global environment}

remove(list = ls())

```

#Call libraries

```{r Install packages}

#install.packages("tidyverse")

```

```{r Load libraries}

library(tidyverse)

```

#Add colour palette

```{r Create colour palettes}

glad_coping_palette2 <- c("#EFC10B", "#B7DEE8")

```


#Source data paths

```{r Source paths}

source("..//COPING_participation_paths.r")

```

#Source functions

```{r Source functions}

source("..//COPING_participation_functions.r")

```

```{r Read in glad coping participation data}

glad_coping_participation <- read_rds(paste0(processed_data_path, processed_data_name))

#Check data
glad_coping_participation %>% 
  head()

```

#Plots

Will create individual plots of demographic variables before combining them into
one plot. This includes:

- Age
- Gender
- Employment
- Ethnic identity

```{r Plot age within the GLAD sign up}

age_group_plot <- glad_coping_participation %>% 
  ggplot(aes(x = age_groups_labelled, fill = completed_baseline_labelled)) +
  geom_bar(position = "dodge") +
  labs(x = "Age (years)",
       y = "N participants") +
  scale_fill_manual(values = glad_coping_palette2) +
  theme(axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black")) +
  theme_classic() +
  theme(legend.position = "none")

#Check plot
age_group_plot

```

```{r Plot gender within the glad sign up}

gender_plot <- glad_coping_participation %>% 
  ggplot(aes(x = gender_recode_labelled, fill = completed_baseline_labelled)) +
  geom_bar(position = "dodge") +
  labs(x = "Gender",
       y = "N participants") +
  scale_fill_manual(values = glad_coping_palette2) +
  theme(axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black")) +
  theme_classic() +
  theme(legend.position = "none")

#Check plot
gender_plot

```

```{r Plot employment in the GLAD sign up}

employment_plot <- glad_coping_participation %>% 
  drop_na(employment_labelled) %>% 
  ggplot(aes(x = employment_labelled, fill = completed_baseline_labelled)) +
  geom_bar(position = "dodge") +
  labs(x = "Employment status",
       y = "N participants") +
  scale_fill_manual(values = glad_coping_palette2) +
  scale_x_discrete(guide = guide_axis(n.dodge = 3)) +
  theme(axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black")) +
  theme_classic() +
  theme(legend.position = "none")

#Check plot
employment_plot

```

```{r Plot ethnicity in the GLAD sign up}

ethnicity_plot <- glad_coping_participation %>% 
  drop_na(ethnicity_labelled) %>% 
  ggplot(aes(x = ethnicity_labelled, fill = completed_baseline_labelled)) +
  geom_bar(position = "dodge") +
  labs(x = "Ethnic identity",
       y = "N participants") +
  scale_fill_manual(values = glad_coping_palette2) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  theme(axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black")) +
  theme_classic() +
  theme(legend.position = "none")

#Check plot
ethnicity_plot

```
